FROM apache/airflow:2.8.2-python3.10

USER root

# Install Java (required for PySpark)
RUN apt-get update && apt-get install -y openjdk-17-jdk
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH="$JAVA_HOME/bin:$PATH"

COPY airflow/dags /opt/airflow/dags
COPY ml_pipeline /opt/ml_pipeline
COPY data /data
COPY requirements.txt /requirements.txt

USER airflow

RUN pip install --no-cache-dir -r /requirements.txt