FROM python:3.10
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY rag_pipeline/ .
COPY data /data
CMD ["uvicorn", "rag_api:app", "--host", "0.0.0.0", "--port", "8000"]